# Generated by Django 3.2.23 on 2024-01-05 14:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_alter_reservation_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='time',
            field=models.TimeField(choices=[(datetime.time(12, 0), '12:00pm - 1:45pm'), (datetime.time(14, 0), '2:00pm - 3:45pm'), (datetime.time(16, 0), '4:00pm - 5:45pm'), (datetime.time(18, 0), '6:00pm - 7:45pm'), (datetime.time(20, 0), '8:00pm - 9:45pm')], default=datetime.time(12, 0)),
        ),
    ]
